---
- hosts: 172.31.21.9 
  become: yes
  tasks:
  - name: i want to execute  linux command
    command: hostname -f
    register:  myresult
    
  - name: i want to  display my first tast  result
    debug:
       msg: "{{myresult}}"


  - name: i want to install git
    apt:
      name: git
      state: present
    when: myresult.stderr==""

  - name: i want to install tree
    apt:  
      name: tree
      state: present
    when: myresult.stderr !=""


